language: node_js
node_js:
  - "9.8.0"

cache:
  directories:
    - node_modules
    - "$HOME/.npm"

stages:
  - name: test
  - name: deploy
    if: branch = master AND NOT type = pull_request

jobs:
  include:
    - stage: test
      install:
        - npm install -g npm@5.7.1
        - npm ci
      script:
        - npm test
    - stage: deploy
      install:
        - npm install -g npm@5.7.1
        - npm ci
      script:
        - echo "Deploying";
        - git config --global user.email "login+travis@elo7.com"
        - git config --global user.name "Travis ci"
        - git remote rm origin
        - git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$TRAVIS_REPO_SLUG.git"
        - npm run deploy
        - echo "Deployed";
